import "./globals.css";
import { PlayersProvider } from "./context/PlayersContext";


export const metadata = {
  title: "Truth & Dare",
  description: "Generated by erehh",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PlayersProvider>{children}</PlayersProvider>
      </body>
    </html>
  );
}
